### ISSUE TITLE
Supplier Page

### ISSUE THREAD

**Issue by VinayCSE85** [VinayCSE85/MeDEcentral#3]
Show the actions on each page as tiles
Action 1
- View Orders
    - Will display list of orders
    - Each order will have the following details
        - Creator Name
        - Order Number
        - Order Description
        - Order Amount
        - Order Quantity
        - Order Status 
    - And list will also contain these actions for each item
        - Take Action

There are 3 states for Order Status - Open, In Process, Closed.
The take action button should show the next state's name based on the current state.
- If order is open, take action will display Accept Order
- If order is In Process, take action will display Close Order
- If order is closed, take action will be disabled

For now, just keep a simple button with the text "Take Action"

**Comment by VinayCSE85** [comment]
Action 2
- Procure Product
- Will open a form with the following fields
    - Product Name
    - Type of Product (Dropdown with Values - RawMaterial, IntermediaryProduct, FinishedProduct)
    - Product Description
    - Product Quantity
    - Product Price
    - Product Status
    - Product Location
And a submit button at the end.

**Comment by VinayCSE85** [comment]
Action 3
- View Inventory
- Lists the products in the inventory of the Supplier. Fields will be same as the form fields above.

**Comment by VinayCSE85** [comment]
Action 4
- Handover Product
- Will Contain 3 dropdowns, one for selecting the order, second for selecting the product, third for selecting the transporter
- there will be one input field for selecting the quantity of the product
- finally, a submit button that will transfer the ownership of product from supplier to transporter.

**Comment by vilas-shivamallu** [comment]
https://github.com/VinayCSE85/MeDEcentral/pull/7
